name: Create and publish a Docker image

on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Install dependencies
        run: |
          npm install

      - name: Build app
        # Sadly we have to include a cookie secret so the build can succeed
        run: |
          JWT_SECRET=ieuwfgzveriowq7rtfheriow3u VITE_VERSION=${{ steps.meta.outputs.tags }} npm run build

      - name: Remove node_modules
        run: |
          rm -r node_modules

      - name: Install production dependencies
        run: |
          npm ci --prod

      - name: Copy package.json
        run: |
          cp package.json build

      - name: Copy node_modules
        run: |
          cp -r node_modules build

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
